// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZjrCChO_9RXRykyc1TB_rg-LVSfay3E',
    appId: '1:634427102282:web:ccb332e6c1654ef05f82b3',
    messagingSenderId: '634427102282',
    projectId: 'lizquet-app',
    authDomain: 'lizquet-app.firebaseapp.com',
    storageBucket: 'lizquet-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEH3OClNwIC4SLwIVQ9nu4Uhw7eD0VO0o',
    appId: '1:634427102282:android:e673b3e612a1502e5f82b3',
    messagingSenderId: '634427102282',
    projectId: 'lizquet-app',
    storageBucket: 'lizquet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ-3IjP8oak3otclSLlJMWFXAQZ-ECWYM',
    appId: '1:634427102282:ios:aaf6dbdf272d7dc95f82b3',
    messagingSenderId: '634427102282',
    projectId: 'lizquet-app',
    storageBucket: 'lizquet-app.firebasestorage.app',
    iosClientId: '634427102282-3g025aguelaa5bfkva55pkui4gm195kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lizquetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ-3IjP8oak3otclSLlJMWFXAQZ-ECWYM',
    appId: '1:634427102282:ios:aaf6dbdf272d7dc95f82b3',
    messagingSenderId: '634427102282',
    projectId: 'lizquet-app',
    storageBucket: 'lizquet-app.firebasestorage.app',
    iosClientId: '634427102282-3g025aguelaa5bfkva55pkui4gm195kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.lizquetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZjrCChO_9RXRykyc1TB_rg-LVSfay3E',
    appId: '1:634427102282:web:3cb822aa830cba7f5f82b3',
    messagingSenderId: '634427102282',
    projectId: 'lizquet-app',
    authDomain: 'lizquet-app.firebaseapp.com',
    storageBucket: 'lizquet-app.firebasestorage.app',
  );
}
